### ISSUE TITLE
Publish type declarations

### ISSUE THREAD

**Issue by johngeorgewright** [nutriot/bandcamp-api#11]
I just installed a fresh copy of `@nutriot/bandcamp-api@0.4.1` but there are no type declarations. It would be great if you could add those to the published package.

**Comment by idleberg** [comment]
You could give the current `main`-branch a try, it has both type declarations and (incomplete) Zod schemas. Other than that you don't really risk anything, the rest of the code is about the same as the latest release. I'd appreciate some feedback.

The incomplete schemas and an outdated test needs to be fixed (actually, the test will probably run find, I need to update my test data).

**Comment by idleberg** [comment]
Update: I'm hoping to release a new version at the end of this week!

**Comment by idleberg** [comment]
v0.5 is now available

**Comment by idleberg** [comment]
The existing types should now be properly exposed using the 0.5 versions. However, the response types are work-in-progress, since there's no official documentation on them. I started creating Zod schemas for these, but I'm not sure the date from my own Bandcamp data is sufficient. In other words, I'm happy for PRs.
